<?php
$news = $this->getNews();
if ($news):
    foreach ($news as $article):
        ?>
        <div class="news">
            <h2>
                <a href="<?php echo $article->getUrl() ?>">
                    <?php echo $article->getTitle(); ?>
                </a>
            </h2>
            <img src="<?php echo $article->getImageUrl(); ?>" alt="<?php echo $article->getTitle(); ?>">
            <div class="text">
                <?php echo $article->getDescription(); ?>
            </div>
        </div>
        <hr/>
        <?php endforeach; ?>
<?php endif; ?>
